version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-quest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass

volumes:
  postgres-volume:
    external: false

networks:
  default:
    name: postgres-network
    driver: bridge
